name: Deploy mdBook site to GitHub Pages

on:
  push:
    branches: ["deploy"]  
  pull_request:
  repository_dispatch:
    types: [deploy-pages]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30

      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.5.0-beta.1'  # 建议指定一个稳定版本
      - name: Prepare source directory
        run: |
          if [ ! -f "src/SUMMARY.md" ]; then
            mkdir -p src
            mv SUMMARY.md src/
            mv README.md src/
            mv operation-manual src/
            mv provernet-architecture src/
            mv user-tutorial src/
          fi
      - name: Build with mdBook
        run: | 
            mdbook clean
            mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book 