name: Deploy mdBook site to GitHub Pages (deploy branch)

on:
  push:
    branches: ["deploy"]  
  pull_request:
  repository_dispatch:
    types: [deploy-pages]
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: deploy  # 确保检出 deploy 分支的最新代码  

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.5.0-beta.1'

      - name: Prepare source directory
        run: |
          if [ ! -f "src/SUMMARY.md" ]; then
            mkdir -p src
            mv SUMMARY.md src/
            mv README.md src/
            mv operation-manual src/
            mv provernet-architecture src/
            mv user-tutorial src/
          fi

      - name: Build with mdBook
        run: | 
            mdbook clean
            mdbook build
      - name: Copy CNAME to book directory
        run: cp CNAME ./book/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book 